parameters:
#    provip_user.example.class: Provip\UserBundle\Example

services:
#    provip_user.example:
#        class: %provip_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
