parameters:
    user_form_factory.class: Provip\UserBundle\Factory\UserFormFactory

services:
    provip.user_form_factory:
        class:     %user_form_factory.class%
        arguments: [@form.factory]