provip_events:
    resource: "@ProvipEventsBundle/Controller/"
    prefix:   /
    type: annotation

provip_provip:
    resource: "@ProvipProvipBundle/Controller/"
    prefix:   /
    type: annotation

provip_user:
    resource: "@ProvipUserBundle/Controller/"
    prefix:   /
    type: annotation
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_imagine:
    resource: .
    type:     imagine