parameters:
#    provip_events.example.class: Provip\EventsBundle\Example

services:
#    provip_events.example:
#        class: %provip_events.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
