parameters:
#    provip_application.example.class: Provip\ApplicationBundle\Example

services:
#    provip_application.example:
#        class: %provip_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
